#!/usr/bin/env bash
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is a multiple of 3
# displays Buzz when the number is a multiple of 5
# else, displays the number in a list format
for ((n=1;n<=100;n++))
do
    if ((n % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((n % 3 == 0))
    then
        echo "Fizz"
    elif ((n % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$n"
    fi
done
