#!/usr/bin/env bash
# loops from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th element
# displays 9 and then bad luck from Japan for the 8th element
# displays 17 and then bad luck from Italy for the 17th element
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	     4) echo "bad luck from China"
	     	;;
	     9) echo "bad luck from Japan"
	        ;;
	     17) echo "bad luck from Italy"
	        ;;
        esac
	i=$((i+1))
done
